# Generated by Django 3.1.7 on 2021-03-27 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(help_text='Enter the book name', max_length=200)),
                ('author', models.CharField(help_text="Enter the book's author name", max_length=200)),
                ('published_by', models.CharField(max_length=200)),
                ('tags', models.CharField(choices=[('ACTION', 'Action'), ('THRILLER', 'Thriller'), ('ART', 'Art'), ('ROMANCE', 'Romance'), ('FAIRYTALE', 'Fairytale'), ('TRUE CRIME', 'True_crime'), ('DRAMA', 'Drama'), ('DIARY', 'Diary'), ('COMIC', 'Comic'), ('HISTORY', 'History'), ('HORROR', 'Horror')], default='ACTION', max_length=20)),
                ('types', models.CharField(choices=[('Firsthand', 'Firsthand'), ('Secondhand', 'Secondhand')], default='Secondhand', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, help_text="Enter the book's price", max_digits=5)),
                ('pin_code', models.CharField(help_text='Enter the pincode of your suitable area to sell', max_length=10)),
                ('description', models.TextField(help_text='Please add if any extra info is there for the book', max_length=300, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
