# Generated by Django 3.2.2 on 2021-05-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='count',
        ),
    ]
