# Generated by Django 3.2.2 on 2021-05-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_remove_cart_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_list',
        ),
    ]
